# DockSTARTer override file for samba.
# please check the developer site for full setup and config => https://github.com/dperson/samba
# This override makes use of the .env file located in the same location where your override should be.
#
# I made this override so I could as window user edit/view config files and logs.
# This will make it possible to access the following folders backup, compose, .docker
# after enabling in DockSTARTer you need to edit the samba settings in the .env
# changed network_mode to "host" or else it wouldn't show up in my network.
# NOTE: change "username" to your username used on your system line 15,23,24,25
# NOTE: change the "WORKGROUP" to your workgroup name line 17
  samba:
    network_mode: "host"
    command:
      -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}"
      -s "DockSTARTer;/username/;yes;no;yes;all;${SAMBA_USERNAME}"
    environment:
      - WORKGROUP=WORKGROUP
      - NMBD=true
    ports:
      - 137:137/udp
      - 138:138/udp
    volumes:
      - ${BACKUP_CONFDIR}:/username/backup
      - ${DOCKERCONFDIR}:/username/docker/config
      - /home/username/.docker/compose:/username/compose
      - ${DOCKERCONFDIR}/samba:/etc/samba